/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package main

import (
	"log"

	// WARNING!
	// Pass --git-repo-id and --git-user-id properties when generating the code
	//
	"github.com/GIT_USER_ID/GIT_REPO_ID/db"
	sw "github.com/GIT_USER_ID/GIT_REPO_ID/go"
)

func main() {
	db.InitDatabase()
	defer db.CloseDatabase()
	routes := sw.ApiHandleFunctions{
		EventosAPI:  sw.EventosAPI{DB: db.Session},
		UsuariosAPI: sw.UsuariosAPI{DB: db.Session},
	}

	log.Printf("Server started")

	router := sw.NewRouter(routes)

	log.Fatal(router.Run(":8080"))
}
