/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
	"github.com/gocql/gocql"
)

type EventosAPI struct {
	DB *gocql.Session
}

// Post /compras/albumes
// Registrar compra de album
func (api *EventosAPI) ComprasAlbumesPost(c *gin.Context) {
	var req CompraAlbum

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "JSON invalido"})
		return
	}

	err := req.storeAlbumOrder(api.DB)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"status": "error", "message": err.Error()})
	}
	c.JSON(200, gin.H{
		"status": "OK",
	})
}

// Post /compras/merchandising
// Registrar compra de merchandising
func (api *EventosAPI) ComprasMerchandisingPost(c *gin.Context) {
	var req CompraMerch

	if err := c.ShouldBindJSON(&req); err != nil {
		c.JSON(http.StatusBadRequest, gin.H{"error": "JSON invalido"})
		return
	}

	err := req.storeMerchOrder(api.DB)
	if err != nil {
		c.JSON(http.StatusInternalServerError, gin.H{"status": "error", "message": err.Error()})
	}
	// Your handler implementation
	c.JSON(200, gin.H{
		"status": "OK",
	})
}

// Post /escuchas
// Registrar una nueva escucha de cancion
func (api *EventosAPI) EscuchasPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}
