/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type DefaultAPI struct {
}

// Post /compras/albumes
// Registrar compra de album 
func (api *DefaultAPI) ComprasAlbumesPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /compras/merchandising
// Registrar compra de merchandising 
func (api *DefaultAPI) ComprasMerchandisingPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Post /escuchas
// Registrar una nueva escucha de cancion 
func (api *DefaultAPI) EscuchasPost(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /estadisticas/albumes/:idAlbum
// Obtener estadisticas de un album 
func (api *DefaultAPI) EstadisticasAlbumesIdAlbumGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /estadisticas/canciones/:idCancion
// Obtener estadisticas de una cancion 
func (api *DefaultAPI) EstadisticasCancionesIdCancionGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /estadisticas/merchandising/:idMerch
// Obtener estadisticas de un producto de merchandising 
func (api *DefaultAPI) EstadisticasMerchandisingIdMerchGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /ranking/canciones
// Obtener ranking de canciones mas escuchadas 
func (api *DefaultAPI) RankingCancionesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario/estadisticas
// Obtener estadisticas de consumo de un usuario 
func (api *DefaultAPI) UsuariosIdUsuarioEstadisticasGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /usuarios/:idUsuario/historialCompras
// Obtener historial de compras de un usuario 
func (api *DefaultAPI) UsuariosIdUsuarioHistorialComprasGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

