/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"github.com/gin-gonic/gin"
)

type MetricasAPI struct {
}

// Get /estadisticas/albumes/:idAlbum
// Obtener estadisticas de un album 
func (api *MetricasAPI) EstadisticasAlbumesIdAlbumGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /estadisticas/canciones/:idCancion
// Obtener estadisticas de una cancion 
func (api *MetricasAPI) EstadisticasCancionesIdCancionGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /estadisticas/merchandising/:idMerch
// Obtener estadisticas de un producto de merchandising 
func (api *MetricasAPI) EstadisticasMerchandisingIdMerchGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

// Get /ranking/canciones
// Obtener ranking de canciones mas escuchadas 
func (api *MetricasAPI) RankingCancionesGet(c *gin.Context) {
	// Your handler implementation
	c.JSON(200, gin.H{"status": "OK"})
}

