/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"
)

type Escucha struct {

	// ID del usuario
	IdUsuario int32 `json:"idUsuario"`

	// ID de la cancion
	IdCancion int32 `json:"idCancion"`

	// Fecha y hora de la escucha
	Fecha time.Time `json:"fecha"`
}
