/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EstadisticasMerch struct {

	// ID del merch
	IdMerch int32 `json:"idMerch"`

	// Numero total de ventas
	TotalVentas int32 `json:"totalVentas"`

	// Numero de ventas en el ultimo mes
	VentasUltimoMes int32 `json:"ventasUltimoMes"`
}
