/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type HistorialCompras struct {
	ComprasAlbumes       []HistorialComprasAlbumes       `json:"comprasAlbumes"`
	ComprasMerchandising []HistorialComprasMerchandising `json:"comprasMerchandising"`
}
