/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"

	"github.com/gocql/gocql"
)

type CompraMerch struct {
	IdUsuario int32     `json:"idUsuario"`
	IdMerch   int32     `json:"idMerch"`
	Fecha     time.Time `json:"fecha"`
	Cantidad  int32     `json:"cantidad"`
}

func (cm *CompraMerch) storeMerchOrder(session *gocql.Session) error {
	query := `INSERT INTO compraMerch (idUsuario,idMerch,fecha,cantidad)
	VALUES (?,?,?,?)
	`

	err := session.Query(query, cm.IdUsuario, cm.IdMerch, cm.Fecha, cm.Cantidad).Exec()
	if err != nil {
		return err
	}
	return nil
}
