/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EstadisticasCancion struct {

	// ID de la cancion
	IdCancion int32 `json:"idCancion"`

	// Numero total de reproducciones
	TotalEscuchas int32 `json:"totalEscuchas"`

	// Numero de reproducciones en el ultimo mes
	EscuchasUltimoMes int32 `json:"escuchasUltimoMes"`
}
