/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"time"

	"github.com/gocql/gocql"
)

type CompraAlbum struct {
	IdUsuario int32     `json:"idUsuario"`
	IdAlbum   int32     `json:"idAlbum"`
	Fecha     time.Time `json:"fecha"`
}

func (a *CompraAlbum) storeAlbumOrder(session *gocql.Session) error {
	query := `
	INSERT INTO compraAlbum (idUsuario,idAlbum,fecha)
	VALUES (?, ?, ?)
	`

	err := session.Query(query, a.IdUsuario, a.IdAlbum, a.Fecha).Exec()
	if err != nil {
		return err
	}
	return nil
}
