/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type EstadisticasUsuario struct {

	// ID del usuario
	IdUsuario int32 `json:"idUsuario"`

	// Numero total de reproducciones que el usuario ha efectuado
	TotalEscuchas int32 `json:"totalEscuchas"`

	// Numero total de compras de albumes que el usuario ha efectuado
	TotalComprasAlbumes int32 `json:"totalComprasAlbumes"`

	// Numero total de compras de merchandising que el usuario ha efectuado
	TotalComprasMerch int32 `json:"totalComprasMerch"`
}
