/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

type RankingCancion struct {

	// ID de la cancion
	IdCancion int32 `json:"idCancion"`

	// Nombre de la cancion
	NombreCancion string `json:"nombreCancion"`

	// Cantidad de escuchas de la cancion
	Escuchas int32 `json:"escuchas"`

	// Posicion de la cancion en el ranking
	Posicion int32 `json:"posicion"`
}
