/*
 * Microservicio de Estadisticas - GA04
 *
 * Especificacion OpenAPI del microservicio de \"Estadisticas\" dentro del proyecto \"Undersounds\" de GPS/ASEE.  El codigo del proyecto esta disponible en el [repositorio de GitHub](https://github.com/UniExtremadura/proyecto-gps-25-26-ga05).
 *
 * API version: 0.1.0
 * Generated by: OpenAPI Generator (https://openapi-generator.tech)
 */

package openapi

import (
	"net/http"

	"github.com/gin-gonic/gin"
)

// Route is the information for every URI.
type Route struct {
	// Name is the name of this Route.
	Name		string
	// Method is the string for the HTTP method. ex) GET, POST etc..
	Method		string
	// Pattern is the pattern of the URI.
	Pattern	 	string
	// HandlerFunc is the handler function of this route.
	HandlerFunc	gin.HandlerFunc
}

// NewRouter returns a new router.
func NewRouter(handleFunctions ApiHandleFunctions) *gin.Engine {
	return NewRouterWithGinEngine(gin.Default(), handleFunctions)
}

// NewRouter add routes to existing gin engine.
func NewRouterWithGinEngine(router *gin.Engine, handleFunctions ApiHandleFunctions) *gin.Engine {
	for _, route := range getRoutes(handleFunctions) {
		if route.HandlerFunc == nil {
			route.HandlerFunc = DefaultHandleFunc
		}
		switch route.Method {
		case http.MethodGet:
			router.GET(route.Pattern, route.HandlerFunc)
		case http.MethodPost:
			router.POST(route.Pattern, route.HandlerFunc)
		case http.MethodPut:
			router.PUT(route.Pattern, route.HandlerFunc)
		case http.MethodPatch:
			router.PATCH(route.Pattern, route.HandlerFunc)
		case http.MethodDelete:
			router.DELETE(route.Pattern, route.HandlerFunc)
		}
	}

	return router
}

// Default handler for not yet implemented routes
func DefaultHandleFunc(c *gin.Context) {
	c.String(http.StatusNotImplemented, "501 not implemented")
}

type ApiHandleFunctions struct {

	// Routes for the EventosAPI part of the API
	EventosAPI EventosAPI
	// Routes for the MetricasAPI part of the API
	MetricasAPI MetricasAPI
	// Routes for the UsuariosAPI part of the API
	UsuariosAPI UsuariosAPI
}

func getRoutes(handleFunctions ApiHandleFunctions) []Route {
	return []Route{ 
		{
			"ComprasAlbumesPost",
			http.MethodPost,
			"/compras/albumes",
			handleFunctions.EventosAPI.ComprasAlbumesPost,
		},
		{
			"ComprasMerchandisingPost",
			http.MethodPost,
			"/compras/merchandising",
			handleFunctions.EventosAPI.ComprasMerchandisingPost,
		},
		{
			"EscuchasPost",
			http.MethodPost,
			"/escuchas",
			handleFunctions.EventosAPI.EscuchasPost,
		},
		{
			"EstadisticasAlbumesIdAlbumGet",
			http.MethodGet,
			"/estadisticas/albumes/:idAlbum",
			handleFunctions.MetricasAPI.EstadisticasAlbumesIdAlbumGet,
		},
		{
			"EstadisticasCancionesIdCancionGet",
			http.MethodGet,
			"/estadisticas/canciones/:idCancion",
			handleFunctions.MetricasAPI.EstadisticasCancionesIdCancionGet,
		},
		{
			"EstadisticasMerchandisingIdMerchGet",
			http.MethodGet,
			"/estadisticas/merchandising/:idMerch",
			handleFunctions.MetricasAPI.EstadisticasMerchandisingIdMerchGet,
		},
		{
			"RankingCancionesGet",
			http.MethodGet,
			"/ranking/canciones",
			handleFunctions.MetricasAPI.RankingCancionesGet,
		},
		{
			"UsuariosIdUsuarioEstadisticasGet",
			http.MethodGet,
			"/usuarios/:idUsuario/estadisticas",
			handleFunctions.UsuariosAPI.UsuariosIdUsuarioEstadisticasGet,
		},
		{
			"UsuariosIdUsuarioHistorialComprasGet",
			http.MethodGet,
			"/usuarios/:idUsuario/historialCompras",
			handleFunctions.UsuariosAPI.UsuariosIdUsuarioHistorialComprasGet,
		},
	}
}
